/**:
  ros__parameters:
    can_interface: "can0"
    joint_names: ["joint_1"]
    motor_ids: [11]
    default_kp: 50.0
    default_kd: 1.0
    velocity_limit: 20.0
    torque_limit: 20.0
    publish_rate_hz: 50.0
